// <auto-generated />
using System;
using HVAC.EnergyMonitor.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVAC.EnergyMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.AlarmRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AckTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LimitValue")
                        .HasColumnType("REAL");

                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TriggerTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("TriggerValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.HasIndex("TriggerTime");

                    b.ToTable("AlarmRecords");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.AlarmRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HighLimit")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LowLimit")
                        .HasColumnType("REAL");

                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.ToTable("AlarmRules");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaudRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProtocolType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanIntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialPortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte>("SlaveAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ByteOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FunctionCode")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HighLimit")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LowLimit")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Offset")
                        .HasColumnType("REAL");

                    b.Property<int>("RegisterAddress")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Scale")
                        .HasColumnType("REAL");

                    b.Property<bool>("StoreHistory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.PointValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PointId", "Timestamp");

                    b.ToTable("PointValues");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.SyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSyncedRowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableName")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.AlarmRecord", b =>
                {
                    b.HasOne("HVAC.EnergyMonitor.Models.Entities.Point", "Point")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.AlarmRule", b =>
                {
                    b.HasOne("HVAC.EnergyMonitor.Models.Entities.Point", "Point")
                        .WithMany("AlarmRules")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.Point", b =>
                {
                    b.HasOne("HVAC.EnergyMonitor.Models.Entities.Device", "Device")
                        .WithMany("Points")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.PointValue", b =>
                {
                    b.HasOne("HVAC.EnergyMonitor.Models.Entities.Point", "Point")
                        .WithMany("Values")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.Device", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("HVAC.EnergyMonitor.Models.Entities.Point", b =>
                {
                    b.Navigation("AlarmRules");

                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
